datasets:
  laion:
    data_type: images
    build_info:
      storage:
        - dataset/laion/laion_dataset/{00000..10488}.tar
        - dataset/laion/laion_dataset_v1/{00000..03877}.tar
        - dataset/laion/laion_dataset_v1/{00000..00988}.tar
